### ISSUE TITLE
收藏无法导入

### ISSUE THREAD

**Issue by ghycn** [gede123/gede123#32]
Mac 系统 chrome 浏览器标签无法导入。

**Comment by muzi86754781** [comment]
win 系统 chrome 浏览器标签无法导入

**Comment by sunmaobin** [comment]
@ghycn @muzi86754781 感谢你们使用歌德书签，收到问题反馈。之前有用户反馈过类似问题，定位出来问题是收藏的网址中有个别特殊URL导致的，你俩可能也是这个情况，虽然这个问题之前解决过，但是应该还没解决彻底。如果你们当急使用，可以单独发给我，我来帮你们人工导入。如果不急，等我修复这个问题，你们再试试。我的QQ：378272446

**Comment by sunmaobin** [comment]
@ghycn @muzi86754781 问题已经修复，请更新Chrome扩展插件，最新版本：4.1.1
