### ISSUE TITLE
像知乎这种，网站获取站点icon失败，应该用默认icon，不然会有点丑

### ISSUE THREAD

**Issue by lichen0501** [gede123/gede123#34]
![image](https://user-images.githubusercontent.com/19141867/38763913-39030a80-3fd8-11e8-9d1f-3a93d339477e.png)

看控制台，是取那个地址取到了，但是请求资源的时候没有请求到
在图片的onerror事件后面加入默认图标的地址就行了

**Comment by sunmaobin** [comment]
@lichen0501 最喜欢你这种提出问题又给出解决方案的童鞋，首先给你承诺，我们将会在V5.0中彻底解决此问题，感谢你的反馈。

**Comment by sunmaobin** [comment]
@lichen0501 此问题已经修复上线，感谢反馈，如还有其他问题，请留言。
