### ISSUE TITLE
站内搜索逻辑有待优化，搜名称有时候必须按删除键才会有想要的结果

### ISSUE THREAD

**Issue by lichen0501** [gede123/gede123#35]
![image](https://user-images.githubusercontent.com/19141867/38765726-89e89624-3ff9-11e8-8b68-46cca2fbe075.png)
站内搜索禅道，没有反应
![image](https://user-images.githubusercontent.com/19141867/38765722-7eb02b64-3ff9-11e8-9c25-9817bcf18ff1.png)
按删除键出结果
![image](https://user-images.githubusercontent.com/19141867/38765748-cbe97160-3ff9-11e8-8220-f2637aa25952.png)
或者先按空格键，再按删除键，出结果
还有一种情况，搜索框失去焦点再获得焦点，即可出现结果

**Comment by sunmaobin** [comment]
@lichen0501 收到反馈。

1. 首先 “搜索框失去焦点再获得焦点，即可出现结果” 就是这么设计的，目的是想让你第一时间看到搜索结果；
1. 其次，对于你提到的搜索结果不准确的问题，我们这边仔细测试过多次，无法重现你说的这种情况。你看看是不是网络问题导致数据查询有延迟造成。如果还没有解决，可以QQ联系我：375208445。感谢你支持歌德书签。

**Comment by sunmaobin** [comment]
@lichen0501 感谢反馈，如果后续还有问题，可以QQ联系我：375208445
