### ISSUE TITLE
站内搜索特定条件下会变成百度搜索

### ISSUE THREAD

**Issue by lichen0501** [gede123/gede123#36]
![image](https://user-images.githubusercontent.com/19141867/38766002-05c85604-3ffe-11e8-9c58-3ff8b6b20c53.png)
站内搜索没有搜索到或者没有选择搜索结果，按enter键
![image](https://user-images.githubusercontent.com/19141867/38766006-10052f2a-3ffe-11e8-9b3a-c48e7a62e0c3.png)
会在新tab页打开新的歌德书签页面
![image](https://user-images.githubusercontent.com/19141867/38766030-7c7c208c-3ffe-11e8-9271-9e557b78b65f.png)

然后第一个歌德书签搜索框就会变成百度搜索结果，而显示还是站内

**Comment by sunmaobin** [comment]
@lichen0501 收到您的反馈，预计本周内会修复此bug（4.22前），感谢您的反馈。

**Comment by sunmaobin** [comment]
@lichen0501 此问题已修复上线，如果还有其它问题，请留言，感谢。
