### ISSUE TITLE
出现了bug

### ISSUE THREAD

**Issue by zhouyu00** [gede123/gede123#37]
我的一个分类出现和另外一个分类内容一模一样的问题，本来应该有的网址却没有

**Comment by sunmaobin** [comment]
@zhouyu00 你刷新下页面，可能是由于切换了分类后，数据没加载回来导致其实页面没切换。所以让你感觉是一样的。如果还没解决告诉我下你的用户名我帮你定位下。

**Comment by zhouyu00** [comment]
> @zhouyu00 你刷新下页面，可能是由于切换了分类后，数据没加载回来导致其实页面没切换。所以让你感觉是一样的。如果还没解决告诉我下你的用户名我帮你定位下。

上午的时候刷新也没用，但是下午已经ok了

**Comment by sunmaobin** [comment]
> > @zhouyu00 你刷新下页面，可能是由于切换了分类后，数据没加载回来导致其实页面没切换。所以让你感觉是一样的。如果还没解决告诉我下你的用户名我帮你定位下。
> 
> 上午的时候刷新也没用，但是下午已经ok了

解决了就好，这个非常抱歉，给你带来了困扰，上午服务器有点不稳定。
